win: battle.cpp
	@echo
	@echo
	@echo
	@clear
	@echo ██████████████ COMPILATION ISSUES:
	@echo
	g++ Entity.cpp Player.cpp Warrior.cpp Bard.cpp Bugbear.cpp EvilMage.cpp flavourtext.cpp functionroll.cpp battle.cpp -std=c++11
	@clear
	@./a.exe

linux: battle.cpp
	@echo
	@echo
	@echo
	@clear
	@echo ██████████████ COMPILATION ISSUES:
	@echo
	g++ Entity.cpp Player.cpp Warrior.cpp Bard.cpp Bugbear.cpp EvilMage.cpp flavourtext.cpp functionroll.cpp battle.cpp -std=c++11
	@clear
	@./a.out

win-test: test.cpp
	@echo
	@echo
	@echo
	@clear
	@echo ██████████████ COMPILATION ISSUES:
	@echo
	g++ Entity.cpp Player.cpp Warrior.cpp Bard.cpp Bugbear.cpp EvilMage.cpp flavourtext.cpp riggedroll.cpp test.cpp -std=c++11
	@clear
	@./a.exe

linux-test: test.cpp
	@echo
	@echo
	@echo
	@clear
	@echo ██████████████ COMPILATION ISSUES:
	@echo
	g++ Entity.cpp Player.cpp Warrior.cpp Bard.cpp Bugbear.cpp EvilMage.cpp flavourtext.cpp riggedroll.cpp test.cpp -std=c++11
	@clear
	@./a.out
